# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  resourceGroupName: coverity
  storageAccountName: coveritystore
  fileShareName: cov-analysis-share
  mntPath: /mnt/$(storageAccountName)/$(fileShareName)
  COVERITY_TOOL_HOME: $(Agent.BuildDirectory)/cov-analysis
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Pull Coverity analysis tool from cache if available
- task: Cache@2
  inputs:
    key: '"v2" | "coverity-analysis-2019.12" | "$(Agent.OS)"'
    path: $(COVERITY_TOOL_HOME)
    cacheHitVar: CACHE_RESTORED
  displayName: 'Cache Coverity Tool Installation'

# If Coverity not cached, mount file share with Coverity analysis package...
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: azure-connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      sh mount-coverity.sh
      df -h

# ... and copy and install Coverity analysis package first.
- script: |
    cd $(Agent.BuildDirectory)
    cp $(mntPath)/cov-analysis-linux64-2019.12.tar.gz .
    cp $(mntPath)/cov-analysis-linux64-2019.12/bin/license.dat .
    tar -xvzf cov-analysis-linux64-2019.12.tar.gz
    mv cov-analysis-linux64-2019.12 cov-analysis
    cp license.dat ./cov-analysis/bin
    rm -rf jre jre7 architecture-analysis sdk dynamic-analysis forcheck doc
  condition: ne(variables.CACHE_RESTORED, 'true')
  displayName: 'Install Coverity'

# Configure Coverity for Java
- script: $(COVERITY_TOOL_HOME)/bin/cov-configure --java
  displayName: 'Configure Coverity'

# Cache Maven local repo to speed things up
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo

# Coverity scan
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-vm'
    projectName: 'Azure Commons Fileupload'
    streamName: 'az-commons-fileupload'
    checkIssues: false
    issueView: 'Outstanding Issues'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: 'mvn -Drat.skip=true -DskipTests=true package'
    coverityRunType: 'buildanalyzecommit'
    allowUntrusted: true

