name: Black Duck

on: workflow_dispatch

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Detect
        run: bash <(curl -s -L https://detect.synopsys.com/detect8.sh) --blackduck.url=${{ secrets.BLACKDUCK_URL }} --blackduck.api.token=${{ secrets.BLACKDUCK_API_TOKEN }}
